### ISSUE TITLE
IE11&IE10 compatibility issues

### ISSUE THREAD

**Issue by withasi** [xiaody/react-lines-ellipsis#1]
see:
[pic](http://p9.qhimg.com/t015f8476557bde155c.png)

**Comment by elijahboston** [comment]
This seems to be caused by the `.find` method used on line 186 in `html.js` -- IE11 doesn't have support for this method.

**Comment by ajoshi0** [comment]
@withasi You can add `import "core-js/modules/es6.array.find";` to fix this on ie10, ie11 in your app

**Comment by Romcol** [comment]
Hi, did you succeed in making it work with IE11? Even polyfilling the module with core-js, I can't seem to make react-lines-ellipsis work. If you have an example with React, I'd be glad :+1: ;)

**Comment by xiaody** [comment]
Close due to inactivity.
