### ISSUE TITLE
Export ResponsiveEllipsis component

### ISSUE THREAD

**Issue by DaemonAlchemist** [xiaody/react-lines-ellipsis#10]
The documentation describes how to create a responsive ellipsis component, but it would be useful to instead export that component so that it doesn't need to be re-defined everywhere it is used.

**Comment by xiaody** [comment]
You can simply create the responsive component once, put it in your project's `components/` folder or so and use it everywhere in your project.

**Comment by DaemonAlchemist** [comment]
... except my project consists of numerous independent modules, many of which would need this functionality.  Thus, I would still need to define the component multiple times in each module.

**Comment by xiaody** [comment]
Really, I don't think this is a big problem. We are focusing on the implement here. Defining and exporting the responsive component is not hard at all. You can even publish a new npm package like `react-responsive-lines-ellipsis`.

**Comment by DaemonAlchemist** [comment]
If it's not hard to do, what's the issue with implementing it here?  It would just be a few more lines in the main index file for another export.  Your package is very useful, so I would rather not pollute NPM with a whole separate package for such a minor tweak.

**Comment by xiaody** [comment]
The `responsiveHOC` can be used for multiple component, currently both the text version and the HTML version. We would need to define and export the responsive version of every of them.

Also the export must not be done in the main index file for the sake of code tree-shaking.
