### ISSUE TITLE
Broken on React 18 double-render Strict mode

### ISSUE THREAD

**Issue by vuryss** [xiaody/react-lines-ellipsis#103]
In React 18 Strict Mode behind the scenes React mounts the element, then unmounts it and then mounts it again.

See here: https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors

This causes the canvas to be removed from the DOM and the calculations could not be made because on the second mount it has the canvas stored in the class, but the element itself is removed from the DOM.

This can easily be fixed if on unmount we also clear the `this.canvas` after removing it from the DOM.

**Comment by vuryss** [comment]
Here is the fix: https://github.com/xiaody/react-lines-ellipsis/pull/104

**Comment by xiaody** [comment]
Released `react-lines-ellipsis@0.15.1`. Thanks for the help.
