### ISSUE TITLE
Sometimes the code by itself cuts off single line into an ellipsis

### ISSUE THREAD

**Issue by prrenish** [xiaody/react-lines-ellipsis#107]
![Screenshot from 2022-07-21 11-55-18](https://user-images.githubusercontent.com/45816962/180144100-b93b67ef-5866-4056-9efa-4a405a3e2a36.png)

I have tried all the options that are available except `break-all` because that will cut of words for me.
This occurs not on a regular interval but on dynamic updated so is there any way to fix this currently have tried everything but still the same.

```
<ResponsiveEllipsis
          component='article'
          className='ellipsis-text'
          text={text}
          maxLine={2}
          trimRight={false}
          onReflow={handleReflow}
          basedOn={"words"}
          ellipsis='...Read More'
          style={{ whiteSpace: "pre-wrap", wordBreak: "break-word" }}
      /> 
```

Thanks in advance

**Comment by xiaody** [comment]
Close due to inactivity and no reproductions. Feel free to reopen with a stackblitz reproduction link.
