### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version ">=16". Got "14.18.1"

### ISSUE THREAD

**Issue by tuantv413** [xiaody/react-lines-ellipsis#108]
I tried to add react-lines-ellipsis@0.15.2 via yarn but i got this error:

<img width="860" alt="image" src="https://user-images.githubusercontent.com/47620385/181886618-b35a6bb1-0eb9-4dbf-ac02-2d3103f25f68.png">

does this latest version not be supported on node v14 anymore?
pls help take a look.
thanks!

**Comment by xiaody** [comment]
Ah ">= 16" is intended for developing this package. I don't think the users need this. Did you enable the npm `engine-strict` config?

**Comment by tuantv413** [comment]
> Ah ">= 16" is intended for developing this package. I don't think the users need this. Did you enable the npm `engine-strict` config?

@xiaody no, I didn't enable it.
should I enable npm `engine-strict`?

**Comment by xiaody** [comment]
Just leave it as default (false).

I've noticed that you are using yarn instead of npm. yarn is by default stricter about `engines`. It gives you errors unlike npm's warns. You can use the [`--ignore-engines`](https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-engines) flag or `yarn config set ignore-engines true` config.

**Comment by dtinth** [comment]
@xiaody It seems that `package.json`’s `engines` also applies to the consumers of the package, not just developers of the project.

If you want to let users consume this package from Node.js ≤ 16 without compatibility warnings/errors, I suggest removing `"engines"` from `package.json`. (It is possible to keep it in the repo and temporarily remove the `"engines"` field just before running `npm publish`.)

**Comment by xiaody** [comment]
@dtinth @tuantv413  You are right. `react-lines-ellipsis@0.15.3` is released without `engines` field.
