### ISSUE TITLE
Goes to next line in the middle of the word

### ISSUE THREAD

**Issue by Nickk4** [xiaody/react-lines-ellipsis#128]
It cuts off in the middle of the word to go to the next line. For example, the code below renders as:
> This is a very long text, just fo
> r testing purposes and nothi...

```
<LinesEllipsis
  text="This is a very long text, just for testing purposes and nothing else"
  maxLine="2"
  ellipsis="..."
  trimRight={true}
  basedOn="letters"
/>
```

My problem is that in the middle of the word `for` it breaks to a next line. I've also tried `basedOn="words"` and `trimRight={false}` but it would still cut of after the `o` in the word `for`.

**Comment by xiaody** [comment]
The breaking of `for` has nothing to do with this component. Check your css `word-break` settings.

**Comment by Nickk4** [comment]
Thanks @xiaody ! It was indeed just a matter of setting a `word-break` in css.
