### ISSUE TITLE
Renders 3 line on first app render

### ISSUE THREAD

**Issue by Pdhenrique** [xiaody/react-lines-ellipsis#129]
browser: Chrome version - 119.0.6045.159 

As an example, I am working on a menuItem component that must have a title and smaller text below. This text would be limited by default to 2 lines. however, when this menuItem is applied to a component that uses it, it is being rendered with 3 lines, and then if it is re-rendered due to some update in the screen proportion, the 2 lines are applied.

![image](https://github.com/xiaody/react-lines-ellipsis/assets/129234362/0ff7ee3f-c817-4d19-a874-554664addc88)

Some properties, much of the stylization were removed from this image to reduce the size of the content.

In the images below I will show the way it is being rendered in my project.

initial render:
![image](https://github.com/xiaody/react-lines-ellipsis/assets/129234362/5bd39bf4-087f-4224-8de0-8ec89a0d5e70)

render after recalculation: 
![image](https://github.com/xiaody/react-lines-ellipsis/assets/129234362/e055e012-6298-4755-bf46-370fe9b35e9e)

_Originally posted by @Pdhenrique in https://github.com/xiaody/react-lines-ellipsis/issues/109#issuecomment-1836513614_

**Comment by xiaody** [comment]
Close due to inactivity and no reproductions. Feel free to reopen with a stackblitz reproduction link.
