### ISSUE TITLE
Add window resize event listener to the component

### ISSUE THREAD

**Issue by stsiarzhanau** [xiaody/react-lines-ellipsis#2]
**Feature request**

Hi, I've found that in your example app you attached a window resize event listener оn App component
```
class App extends Component {
  constructor (props) {
    super(props)
    this.state = {
      text: defaultText,
      maxLine: 3,
      useEllipsis: true,
      renderId: 1
    }
    this.onTextClick = this.onTextClick.bind(this)
    this.onTextKey = this.onTextKey.bind(this)
    this.onTextEdit = debounce(this.onTextEdit.bind(this), 100)
    this.onChangeLines = debounce(this.onChangeLines.bind(this))
    this.onResize = debounce(this.onResize.bind(this), 150)
  }

  componentDidMount () {
    window.addEventListener('resize', this.onResize)
  }

  componentWillUnmount () {
    window.removeEventListener('resize', this.onResize)
  }
```
But it's not very convenient way when writing an app.
Could you attach listeners to LinesEllipsis and HTMLEllipsis components itself, so one can use this functionality just out of the box?

Packages like [react-text-truncate](https://github.com/One-com/react-truncate/blob/master/src/Truncate.js), [shiitake](https://github.com/bsidelinger912/shiitake/blob/master/src/ResizeListener.jsx), [react-truncate](https://github.com/One-com/react-truncate/blob/master/src/Truncate.js), [react-dotdotdot](https://github.com/CezaryDanielNowak/React-dotdotdot/blob/master/src/index.js) use such an approach and it's very convinient (but unfortunately non of the above can handle HTML :wink:).

Thanks in advance.

**Comment by xiaody** [comment]
Hi stsiarzhanau, I have just added a `responsiveHOC` for this feature in v0.6.0, you can try it.
https://github.com/xiaody/react-lines-ellipsis#responsive-to-window-resize-and-orientation-change

**Comment by stsiarzhanau** [comment]
Awesome! Works as expected! Thanks for responsiveness :+1:!
