### ISSUE TITLE
`winWidth` prop on a DOM element

### ISSUE THREAD

**Issue by fedorovsky** [xiaody/react-lines-ellipsis#20]
"react": "^16.4.0",

Warning: React does not recognize the `winWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `winwidth` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by xiaody** [comment]
Fixed in `react-lines-ellipsis@0.11.0`.
