### ISSUE TITLE
Determine if text was truncated or not?

### ISSUE THREAD

**Issue by mweiczorek** [xiaody/react-lines-ellipsis#21]
This would be a feature request, a property that would return a boolean value on whether or not the text was truncated or not, which would aid in adding a "More/Less" button/link based on if it's needed.

**Comment by xiaody** [comment]
The componet does expose a [`isClamped()`](https://github.com/xiaody/react-lines-ellipsis/blob/master/src/index.js#L150-L152) method, though undocumented yet. Is that want you want?

**Comment by mweiczorek** [comment]
Yes, fantastic.
