### ISSUE TITLE
When text is a number react-reflow breaks

### ISSUE THREAD

**Issue by mobilutz** [xiaody/react-lines-ellipsis#22]
I have a situation where I have text for the LinesEllipsis being a number.
This works, until the component is updated, and the `reflow` method is being called.

The problematic line is this:
https://github.com/xiaody/react-lines-ellipsis/blob/master/src/index.js#L82

When `props.text` is i.e. `8` (the number not the string), there is no `.split` method for that.

**Comment by xiaody** [comment]
We only support String for `props.text`. You shall convert your input like

```jsx
  text={String(8)}
```

**Comment by mobilutz** [comment]
Thanks. We did find another workaround.
