### ISSUE TITLE
Whether to support IE browser？

### ISSUE THREAD

**Issue by fengyun2** [xiaody/react-lines-ellipsis#24]
Whether to support IE browser(ie9+)？

**Comment by xiaody** [comment]
The [example](https://github.com/xiaody/react-lines-ellipsis/blob/master/docs/app.js) should work in IE9+ for most cases. You can test it by yourself at https://xiaody.github.io/react-lines-ellipsis/

**Comment by fengyun2** [comment]
@xiaody Thanks.
