### ISSUE TITLE
warning.js:33 Warning: React does not recognize the `winWidth` prop on a DOM element.

### ISSUE THREAD

**Issue by anilljoshi** [xiaody/react-lines-ellipsis#28]
I have used react-lines-ellipsis in my project its working fine but its showing following warning in console. Because of its added winWidth property to dom element at run time . Please let me know how to over come on this
_**Warning: React does not recognize the `winWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `winwidth` instead. If you accidentally passed it from a parent component, remove it from the DOM element.**_

**Comment by xiaody** [comment]
Please try the latest version `v0.13.0`.

**Comment by anilljoshi** [comment]
Resolved Thanks
