### ISSUE TITLE
more/less btn

### ISSUE THREAD

**Issue by huangxiaohao** [xiaody/react-lines-ellipsis#32]
hi, I want to know how to control more/less button? thank you  very much!

你好，请问「查看更多」/「收起」按钮如何设置？ 非常感谢！

**Comment by xiaody** [comment]
It's not a built in feature. You can wrap the component in something like `<div onClick={this.toggleShowAll} />`.

**Comment by huangxiaohao** [comment]
The problem has not been solved for the time being, but thank you very much.
问题暂时还未解决，但是非常感谢。
