### ISSUE TITLE
Responsive to window resize and orientation change doesn't work

### ISSUE THREAD

**Issue by Sinha06** [xiaody/react-lines-ellipsis#35]
I tried `ResponsiveEllipsis`, but it failed at compile time. 
AT https://github.com/xiaody/react-lines-ellipsis/blob/master/src/responsiveHOC.js#L2, it looks for `lodash/debounce`. Shouldn't it be `lodash.debounce` ?

**Comment by xiaody** [comment]
Oops, I think I forget to add `lodash` into dependencies or peerDependencies. Could you please install lodash in your project and try again?

**Comment by xiaody** [comment]
Fixed in v0.15.0
