### ISSUE TITLE
Can we use Span instead of div in html.js

### ISSUE THREAD

**Issue by galliumsoft** [xiaody/react-lines-ellipsis#37]
Hi, i get this error when i use the htmlellipsis component.. As i understand its because of the usage of <div> in the html.js component... can we change it to <span> instead to avoid these errors? 

Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by HTMLEllipsis)
    in span (created by HTMLEllipsis)

**Comment by xiaody** [comment]
This component is designed to be a block level component. There is no reason to render it in a span.
