### ISSUE TITLE
Bug? - When the string does not contain spaces it is not clamped

### ISSUE THREAD

**Issue by creddy** [xiaody/react-lines-ellipsis#39]
It could be that I'm using the component incorrect. Please correct me if I am. 

This is an edge case for sure, but if the string does not contain any spaces it doesn't appear to be clamped. 

From the [demo](https://xiaody.github.io/react-lines-ellipsis/)

<img width="1296" alt="screen shot 2018-10-26 at 5 44 00 pm" src="https://user-images.githubusercontent.com/593138/47595606-ce7c7080-d946-11e8-89c9-bbfb1643f39c.png">

**Comment by xiaody** [comment]
And also you need to add style `overflow-wrap: break-word;` for the element since the demo sets `white-space: pre-wrap;` on it.

react-lines-ellipsis only clamps lines, not width. So you need to tell the browser to wrap the line.

**Comment by aqqzzz** [comment]
same question, even add style `overflow-wrap: break-word;`

**Comment by mzohaibqc** [comment]
@xiaody Facing same issue and even adding style `overflow-wrap: break-word;` did not work

**Comment by JoaoRPF** [comment]
@xiaody is this problem under evaluation? We are facing the same problem, when there's a word that does not contain spaces

**Comment by xiaody** [comment]
> @xiaody is this problem under evaluation? We are facing the same problem, when there's only one word that does not contain spaces

As I have said, this is not a bug IMO. Users need to correctly set the props and style for such cases.
Here is a demo https://codesandbox.io/s/zzx438p7l4.

**Comment by JoaoRPF** [comment]
Check the comments in https://github.com/xiaody/react-lines-ellipsis/pull/45 if you're facing the same problem.
