### ISSUE TITLE
Remove browserify references from package.json

### ISSUE THREAD

**Issue by damassi** [xiaody/react-lines-ellipsis#4]
Wondering, why are [these lines](https://github.com/xiaody/react-lines-ellipsis/blob/master/package.json#L56) needed? I'm getting this error in my env: 

```
Error: Cannot find module 'aliasify' from '/Users/damassi/Sites/artsy/reaction  /node_modules/react-lines-ellipsis'

Error: Cannot find module 'babelify' from '/Users/damassi/Sites/artsy/reaction  /node_modules/react-lines-ellipsis'
```

As background, I'm using this lib in another lib which is then imported by a third app. The third app, when executing the code, runs into issues with Browserify. Since the package is compiled by babel, why force these additional steps on the consumer?

**Comment by xiaody** [comment]
Didn't know that browserify reads `package.json#browserify#transform` even for modules in `/node_modules`. v0.8.0 renames those lines to `browserify#docs` because they are only used for building the github pages. Hope it works for you!

**Comment by damassi** [comment]
Thank you!
