### ISSUE TITLE
react-dom.js:512 Warning: React does not recognize the `ellipsisHTML` prop on a DOM element

### ISSUE THREAD

**Issue by lushijie** [xiaody/react-lines-ellipsis#40]
0.13.2

react-dom.js:512 Warning: React does not recognize the `ellipsisHTML` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ellipsishtml` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by xiaody** [comment]
I guess you're using `ellipsisHTML` on `LinesEllipsis`. But it is only supported in `HTMLEllipsis`.
