### ISSUE TITLE
there is a space between the ellipsis and the string

### ISSUE THREAD

**Issue by ruhaise** [xiaody/react-lines-ellipsis#43]
im using `HTMLEllipsis` module from the library since i want to trim an html element, but afer the trim happens there is a white space between the ellipsis and word, im sorry if im doing something wrong here, screenshot is attached for reference

![image](https://user-images.githubusercontent.com/25627383/52348601-035b9180-2a25-11e9-805a-a157161ca451.png)

this is the span that causing the extra space between

`<span class="LinesEllipsis-unit"> </span>`

**Comment by xiaody** [comment]
As the [README](https://github.com/xiaody/react-lines-ellipsis#experimental-html-truncation) said, `HTMLEllipsis` does not support trimming.
