### ISSUE TITLE
... needs different color from text(show more)

### ISSUE THREAD

**Issue by momofan** [xiaody/react-lines-ellipsis#44]
just like this：
![image](https://user-images.githubusercontent.com/3773790/53789259-ff0c9080-3f5e-11e9-8aac-0768bbf0d5d2.png)

**Comment by namlq93** [comment]
> just like this：
> ![image](https://user-images.githubusercontent.com/3773790/53789259-ff0c9080-3f5e-11e9-8aac-0768bbf0d5d2.png)

what is your solution?
