### ISSUE TITLE
Module is not supporting style animation.

### ISSUE THREAD

**Issue by madhav-b** [xiaody/react-lines-ellipsis#47]
I had tried to apply style animation with react-line-ellipsis module but can't get any working solution. Transition element is not supporting with this module, Please let me know anyone who faced this issue and resolved.

Here is my code:

```
**index.tsx**
<div>
  <h6>{title}</h6>
  <LinesEllipsis
    text={description}
    maxLine={this.state.maxLine}
    ellipsis='...'
    basedOn='letters'
    />  
  <a onClick={this.handleClick}>{this.state.toggle ? "less" : "more" }</a>
</div>


**styles.css**

.LinesEllipsis--clamped {
    transition: all ease-out .2s;
}
```

**Comment by xiaody** [comment]
As far as I can tell, there is no easy way to do animations for this component. A hidden element must be used and manual style calculation is necessary, which is quite dirty.
