### ISSUE TITLE
Issue using ellipsis on one max line

### ISSUE THREAD

**Issue by cmdSka** [xiaody/react-lines-ellipsis#48]
I'm not quite sure if this is an issue:
https://codesandbox.io/s/826jq3n4w9

Problem is, I can't really make react-lines-ellipsis to work on one line texts to make it stay between the wrapper divs without overflowing. Even if I set the maxLine to 1. If this isn't an issue, please have a look and help me find what I'm missing in my implementation.

Thank you!

**Comment by xiaody** [comment]
Looks similar to #39.

And for one line texts, though the component API supports, why not to use pure CSS `text-overflow`?

**Comment by xiaody** [comment]
Close due to inactivity.
