### ISSUE TITLE
移动端长列表在使用的时候会导出白屏，能否优化一下？

### ISSUE THREAD

**Issue by xingyesh** [xiaody/react-lines-ellipsis#54]
复现方式， 列表非常多的时候，快速滚动会出现短暂的白屏。

**Comment by xiaody** [comment]
这个组件本身和滚动没有关系。本身它也不适合在页面上大量使用，你可以使用考虑使用 `-webkit-line-clamp` 的方案，这个包里也有一个简单封装 `LinesEllipsisLoose`。

**Comment by xingyesh** [comment]
嗯呐，感谢回复。 看了下是用了canvas造成的吧，我改了别的方案了

**Comment by xiaody** [comment]
这个组件和 HTMLCanvasElement 也没有关系，虽然有变量名叫 `canvas`。
