### ISSUE TITLE
HTML Experimental support

### ISSUE THREAD

**Issue by snirotem** [xiaody/react-lines-ellipsis#55]
i'm using your package in production and wanted to know why the inner HTML support is Experimental ?

are there any known issues ?
is there a plan to support it non-experimentally ?

thanks.

**Comment by xiaody** [comment]
HTML structure is much more complex than plain text. I'm just not confident enough to claim it as stable.

I'm also using it in production for simple text with links and bolds. There is no reported issue. There is no plan to support it non-experimentally.
