### ISSUE TITLE
Google chrome 76 in windows 10 it's not working

### ISSUE THREAD

**Issue by luisbritescarvalho** [xiaody/react-lines-ellipsis#56]
Works fine in chrome 75. 

Basic sample: https://45tee.csb.app/

**Comment by thelucre** [comment]
Seeing this issue on Chrome `78.0.3904.108` as well. Any thoughts?

**Comment by thelucre** [comment]
The solve is here: https://github.com/xiaody/react-lines-ellipsis/issues/59#issuecomment-528683491

**Comment by xiaody** [comment]
Close due to inactivity and missing reproductions.
