### ISSUE TITLE
Broken with latest Chrome build v76.0.3809.132

### ISSUE THREAD

**Issue by raynigon** [xiaody/react-lines-ellipsis#59]
**Chrome Version:**
![Chrome](https://user-images.githubusercontent.com/10846939/64350366-d2623000-cff8-11e9-98f8-dae9ae0af33f.png)
---
**Result:**
![Result-with-js](https://user-images.githubusercontent.com/10846939/64350367-d2fac680-cff8-11e9-8bac-5f43d8709ac1.png)
---
**Expected Result:**
![Result-without-js](https://user-images.githubusercontent.com/10846939/64350368-d2fac680-cff8-11e9-9d4f-cfa823259b3b.png)

**Comment by cajames** [comment]
We fixed this issue by adding the style `white-space: pre-wrap;` to the ellipsis text class.

**Comment by cameronDz** [comment]
This also started happening with an application I work on that uses this component. Thanks for posting the fix!

**Comment by PiotrSiatkowski** [comment]
<LinesEllipsis style={{ 'white-space': 'pre-wrap' }} ... solved it for me as well. Thx.

**Comment by fenix20113** [comment]
Thanks! You saved my time

**Comment by schmolie** [comment]
I'm running chrome 77.0.3865.90 and the `style={{ whiteSpace: 'pre-wrap' }}` solution does not work for me. Does anyone have an idea on why this is happening or an alternative solution to fix the issue?

**Comment by diogo-codengage** [comment]
Thanks, It works for me

**Comment by farizsofyan** [comment]
`style={{ whiteSpace: 'pre-wrap' }}` also not work all the time for me.
Try to add `word-break: break-all` too, works for my condition

**Comment by keithort** [comment]
As of Chrome 83, the issue still exists. Adding `style={{ whiteSpace: "pre-wrap", wordBreak: "break-all" }}` to the component works.

**Comment by raynigon** [comment]
Workaround exists, closing the issue
