### ISSUE TITLE
Passing null throws unhandled exception

### ISSUE THREAD

**Issue by LeonsBuntis** [xiaody/react-lines-ellipsis#65]
Passing **null** to `Text` param when `BasedOn` param is "letters",  throws unhandled exception.
 
```
Error in /turbo_modules/react-lines-ellipsis@0.14.1/lib/index.js (158:30)
Cannot convert undefined or null to object
```

Here is reproduction:
https://stackblitz.com/edit/react-pfdgmc

**Comment by xiaody** [comment]
Just pass strings. If your text is from a variable, using `|| ''` or `?? ''` can be helpful.
