### ISSUE TITLE
All Dependencies are DevDependencies

### ISSUE THREAD

**Issue by stubar** [xiaody/react-lines-ellipsis#84]
In our nextJs app we have a post build prune command (https://docs.npmjs.com/cli/v7/commands/npm-prune) which removes all dev dependencies.  This has caused react-lines-ellipsis to cause an error when it imports lodash.   Has anyone else come across this?  We have lots of other dependencies and they work fine so I suspect it is because you have no 'dependencies' list.

**Comment by xiaody** [comment]
Are you using the latest (v0.15.0) version? This might be an issue before, but as v0.15.0 we switched the build tool to microbundle which would bundle everything used but not in the dependencies field into the output file.

**Comment by stubar** [comment]
yes we're on 0.15.0

**Comment by xiaody** [comment]
The only thing we require is `react`. You can check the node_modules folder.

```
➜  react-lines-ellipsis pwd
/tmp/test2/node_modules/react-lines-ellipsis
➜  react-lines-ellipsis cat package.json | grep version
  "version": "0.15.0"
➜  react-lines-ellipsis rg require
lib/loose.js
1:var React = require('react');

lib/index.js
1:var React = require('react');

lib/html.js
1:var React = require('react');

package.json
18:  "_requiredBy": [

lib/responsiveHOC.js
1:var React = require('react');

README.md
95:- requires modern browsers env
➜  react-lines-ellipsis
```
