### ISSUE TITLE
Support a width prop

### ISSUE THREAD

**Issue by WORLDI** [xiaody/react-lines-ellipsis#91]
Hello,
I wish to support a width prop, when a text is shorter than width, it just show like text, and when text is longer than width, the text should be cut down and show with an ellipsis. Now i set the style={{width: xxx}} to the component, when text is shorter than width, the component width is not fit-content, it is longer than text's width. Like this:
![image](https://user-images.githubusercontent.com/66404428/136753526-ac1f2f06-2f83-4d22-9108-ae7690f4bf56.png)

**Comment by xiaody** [comment]
If you want to clamp a single line by width, you don't need this component. Just use simple CSS https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow
