### ISSUE TITLE
Text being ellipsed before space runs out

### ISSUE THREAD

**Issue by angeloaltamiranom** [xiaody/react-lines-ellipsis#94]
This is happening when there is text that is in a dash-separated format and there are no whitespaces.

codepen: https://codepen.io/angeloaltamiranom/pen/gOGQbRR

SS:
![react-lines-bug](https://user-images.githubusercontent.com/71276198/149037488-492cb87b-3d5b-4285-9999-8df2f7f44738.PNG)

**Comment by xiaody** [comment]
You need `word-break: break-all;` for your #container. Or browser will try not to break a long word and put it on a seperate line.

![image](https://user-images.githubusercontent.com/1246451/149055770-6887b8ba-8f2d-4538-9ade-7c92151fce8e.png)

**Comment by angeloaltamiranom** [comment]
Thank you @xiaody!
